on: push
name: Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - with:
          fetch-deph: 2
        uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install --legacy-peer-deps --force
      - name: Building the project
        run: npm run build
      - name: Sync files Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
